// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PersistAttrRpc.proto

#ifndef PROTOBUF_PersistAttrRpc_2eproto__INCLUDED
#define PROTOBUF_PersistAttrRpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PublicStruct.pb.h"
// @@protoc_insertion_point(includes)
class PersistAttrRpcSyncDataAsk;
class PersistAttrRpcSyncDataAskDefaultTypeInternal;
extern PersistAttrRpcSyncDataAskDefaultTypeInternal _PersistAttrRpcSyncDataAsk_default_instance_;
class PersistAttrRpcSyncDataReply;
class PersistAttrRpcSyncDataReplyDefaultTypeInternal;
extern PersistAttrRpcSyncDataReplyDefaultTypeInternal _PersistAttrRpcSyncDataReply_default_instance_;

namespace protobuf_PersistAttrRpc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_PersistAttrRpc_2eproto

// ===================================================================

class PersistAttrRpcSyncDataAsk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PersistAttrRpcSyncDataAsk) */ {
 public:
  PersistAttrRpcSyncDataAsk();
  virtual ~PersistAttrRpcSyncDataAsk();

  PersistAttrRpcSyncDataAsk(const PersistAttrRpcSyncDataAsk& from);

  inline PersistAttrRpcSyncDataAsk& operator=(const PersistAttrRpcSyncDataAsk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PersistAttrRpcSyncDataAsk(PersistAttrRpcSyncDataAsk&& from) noexcept
    : PersistAttrRpcSyncDataAsk() {
    *this = ::std::move(from);
  }

  inline PersistAttrRpcSyncDataAsk& operator=(PersistAttrRpcSyncDataAsk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PersistAttrRpcSyncDataAsk& default_instance();

  static inline const PersistAttrRpcSyncDataAsk* internal_default_instance() {
    return reinterpret_cast<const PersistAttrRpcSyncDataAsk*>(
               &_PersistAttrRpcSyncDataAsk_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PersistAttrRpcSyncDataAsk* other);
  friend void swap(PersistAttrRpcSyncDataAsk& a, PersistAttrRpcSyncDataAsk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PersistAttrRpcSyncDataAsk* New() const PROTOBUF_FINAL { return New(NULL); }

  PersistAttrRpcSyncDataAsk* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PersistAttrRpcSyncDataAsk& from);
  void MergeFrom(const PersistAttrRpcSyncDataAsk& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PersistAttrRpcSyncDataAsk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:PersistAttrRpcSyncDataAsk)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct protobuf_PersistAttrRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PersistAttrRpcSyncDataReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:PersistAttrRpcSyncDataReply) */ {
 public:
  PersistAttrRpcSyncDataReply();
  virtual ~PersistAttrRpcSyncDataReply();

  PersistAttrRpcSyncDataReply(const PersistAttrRpcSyncDataReply& from);

  inline PersistAttrRpcSyncDataReply& operator=(const PersistAttrRpcSyncDataReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PersistAttrRpcSyncDataReply(PersistAttrRpcSyncDataReply&& from) noexcept
    : PersistAttrRpcSyncDataReply() {
    *this = ::std::move(from);
  }

  inline PersistAttrRpcSyncDataReply& operator=(PersistAttrRpcSyncDataReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PersistAttrRpcSyncDataReply& default_instance();

  static inline const PersistAttrRpcSyncDataReply* internal_default_instance() {
    return reinterpret_cast<const PersistAttrRpcSyncDataReply*>(
               &_PersistAttrRpcSyncDataReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PersistAttrRpcSyncDataReply* other);
  friend void swap(PersistAttrRpcSyncDataReply& a, PersistAttrRpcSyncDataReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PersistAttrRpcSyncDataReply* New() const PROTOBUF_FINAL { return New(NULL); }

  PersistAttrRpcSyncDataReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PersistAttrRpcSyncDataReply& from);
  void MergeFrom(const PersistAttrRpcSyncDataReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PersistAttrRpcSyncDataReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Result = 1 [default = -9999];
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PersistAttrRpcSyncDataReply)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct protobuf_PersistAttrRpc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PersistAttrRpcSyncDataAsk

// -------------------------------------------------------------------

// PersistAttrRpcSyncDataReply

// optional sint32 Result = 1 [default = -9999];
inline bool PersistAttrRpcSyncDataReply::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PersistAttrRpcSyncDataReply::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PersistAttrRpcSyncDataReply::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PersistAttrRpcSyncDataReply::clear_result() {
  result_ = -9999;
  clear_has_result();
}
inline ::google::protobuf::int32 PersistAttrRpcSyncDataReply::result() const {
  // @@protoc_insertion_point(field_get:PersistAttrRpcSyncDataReply.Result)
  return result_;
}
inline void PersistAttrRpcSyncDataReply::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:PersistAttrRpcSyncDataReply.Result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PersistAttrRpc_2eproto__INCLUDED
