// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZhanDouV1Data.proto

#ifndef PROTOBUF_ZhanDouV1Data_2eproto__INCLUDED
#define PROTOBUF_ZhanDouV1Data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "PublicStruct.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ZhanDouV1Data_2eproto();
void protobuf_AssignDesc_ZhanDouV1Data_2eproto();
void protobuf_ShutdownFile_ZhanDouV1Data_2eproto();

class ZhanDouMoveDataV1;
class ZhanDouUserDataV1;

// ===================================================================

class ZhanDouMoveDataV1 : public ::google::protobuf::Message {
 public:
  ZhanDouMoveDataV1();
  virtual ~ZhanDouMoveDataV1();

  ZhanDouMoveDataV1(const ZhanDouMoveDataV1& from);

  inline ZhanDouMoveDataV1& operator=(const ZhanDouMoveDataV1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZhanDouMoveDataV1& default_instance();

  void Swap(ZhanDouMoveDataV1* other);

  // implements Message ----------------------------------------------

  ZhanDouMoveDataV1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZhanDouMoveDataV1& from);
  void MergeFrom(const ZhanDouMoveDataV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Dir = 1 [default = -1];
  inline bool has_dir() const;
  inline void clear_dir();
  static const int kDirFieldNumber = 1;
  inline ::google::protobuf::int32 dir() const;
  inline void set_dir(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ZhanDouMoveDataV1)
 private:
  inline void set_has_dir();
  inline void clear_has_dir();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 dir_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ZhanDouV1Data_2eproto();
  friend void protobuf_AssignDesc_ZhanDouV1Data_2eproto();
  friend void protobuf_ShutdownFile_ZhanDouV1Data_2eproto();

  void InitAsDefaultInstance();
  static ZhanDouMoveDataV1* default_instance_;
};
// -------------------------------------------------------------------

class ZhanDouUserDataV1 : public ::google::protobuf::Message {
 public:
  ZhanDouUserDataV1();
  virtual ~ZhanDouUserDataV1();

  ZhanDouUserDataV1(const ZhanDouUserDataV1& from);

  inline ZhanDouUserDataV1& operator=(const ZhanDouUserDataV1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ZhanDouUserDataV1& default_instance();

  void Swap(ZhanDouUserDataV1* other);

  // implements Message ----------------------------------------------

  ZhanDouUserDataV1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ZhanDouUserDataV1& from);
  void MergeFrom(const ZhanDouUserDataV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ZhanDouUserDataV1)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_ZhanDouV1Data_2eproto();
  friend void protobuf_AssignDesc_ZhanDouV1Data_2eproto();
  friend void protobuf_ShutdownFile_ZhanDouV1Data_2eproto();

  void InitAsDefaultInstance();
  static ZhanDouUserDataV1* default_instance_;
};
// ===================================================================


// ===================================================================

// ZhanDouMoveDataV1

// optional sint32 Dir = 1 [default = -1];
inline bool ZhanDouMoveDataV1::has_dir() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ZhanDouMoveDataV1::set_has_dir() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ZhanDouMoveDataV1::clear_has_dir() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ZhanDouMoveDataV1::clear_dir() {
  dir_ = -1;
  clear_has_dir();
}
inline ::google::protobuf::int32 ZhanDouMoveDataV1::dir() const {
  return dir_;
}
inline void ZhanDouMoveDataV1::set_dir(::google::protobuf::int32 value) {
  set_has_dir();
  dir_ = value;
}

// -------------------------------------------------------------------

// ZhanDouUserDataV1


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ZhanDouV1Data_2eproto__INCLUDED
