// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ZhanDouRpc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ZhanDouRpc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* ZhanDouRpcMoveAsk_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZhanDouRpcMoveAsk_reflection_ = NULL;
const ::google::protobuf::Descriptor* ZhanDouRpcMoveReply_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZhanDouRpcMoveReply_reflection_ = NULL;
const ::google::protobuf::Descriptor* ZhanDouRpcTalkNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ZhanDouRpcTalkNotify_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ZhanDouRpc_2eproto() {
  protobuf_AddDesc_ZhanDouRpc_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ZhanDouRpc.proto");
  GOOGLE_CHECK(file != NULL);
  ZhanDouRpcMoveAsk_descriptor_ = file->message_type(0);
  static const int ZhanDouRpcMoveAsk_offsets_[1] = {
  };
  ZhanDouRpcMoveAsk_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ZhanDouRpcMoveAsk_descriptor_,
      ZhanDouRpcMoveAsk::default_instance_,
      ZhanDouRpcMoveAsk_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcMoveAsk, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcMoveAsk, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ZhanDouRpcMoveAsk));
  ZhanDouRpcMoveReply_descriptor_ = file->message_type(1);
  static const int ZhanDouRpcMoveReply_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcMoveReply, result_),
  };
  ZhanDouRpcMoveReply_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ZhanDouRpcMoveReply_descriptor_,
      ZhanDouRpcMoveReply::default_instance_,
      ZhanDouRpcMoveReply_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcMoveReply, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcMoveReply, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ZhanDouRpcMoveReply));
  ZhanDouRpcTalkNotify_descriptor_ = file->message_type(2);
  static const int ZhanDouRpcTalkNotify_offsets_[1] = {
  };
  ZhanDouRpcTalkNotify_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ZhanDouRpcTalkNotify_descriptor_,
      ZhanDouRpcTalkNotify::default_instance_,
      ZhanDouRpcTalkNotify_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcTalkNotify, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ZhanDouRpcTalkNotify, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ZhanDouRpcTalkNotify));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ZhanDouRpc_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ZhanDouRpcMoveAsk_descriptor_, &ZhanDouRpcMoveAsk::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ZhanDouRpcMoveReply_descriptor_, &ZhanDouRpcMoveReply::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ZhanDouRpcTalkNotify_descriptor_, &ZhanDouRpcTalkNotify::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ZhanDouRpc_2eproto() {
  delete ZhanDouRpcMoveAsk::default_instance_;
  delete ZhanDouRpcMoveAsk_reflection_;
  delete ZhanDouRpcMoveReply::default_instance_;
  delete ZhanDouRpcMoveReply_reflection_;
  delete ZhanDouRpcTalkNotify::default_instance_;
  delete ZhanDouRpcTalkNotify_reflection_;
}

void protobuf_AddDesc_ZhanDouRpc_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_PublicStruct_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ZhanDouRpc.proto\032\022PublicStruct.proto\"\023"
    "\n\021ZhanDouRpcMoveAsk\",\n\023ZhanDouRpcMoveRep"
    "ly\022\025\n\006Result\030\001 \001(\021:\005-9999\"\026\n\024ZhanDouRpcT"
    "alkNotify", 129);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ZhanDouRpc.proto", &protobuf_RegisterTypes);
  ZhanDouRpcMoveAsk::default_instance_ = new ZhanDouRpcMoveAsk();
  ZhanDouRpcMoveReply::default_instance_ = new ZhanDouRpcMoveReply();
  ZhanDouRpcTalkNotify::default_instance_ = new ZhanDouRpcTalkNotify();
  ZhanDouRpcMoveAsk::default_instance_->InitAsDefaultInstance();
  ZhanDouRpcMoveReply::default_instance_->InitAsDefaultInstance();
  ZhanDouRpcTalkNotify::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ZhanDouRpc_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ZhanDouRpc_2eproto {
  StaticDescriptorInitializer_ZhanDouRpc_2eproto() {
    protobuf_AddDesc_ZhanDouRpc_2eproto();
  }
} static_descriptor_initializer_ZhanDouRpc_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

ZhanDouRpcMoveAsk::ZhanDouRpcMoveAsk()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ZhanDouRpcMoveAsk::InitAsDefaultInstance() {
}

ZhanDouRpcMoveAsk::ZhanDouRpcMoveAsk(const ZhanDouRpcMoveAsk& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ZhanDouRpcMoveAsk::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ZhanDouRpcMoveAsk::~ZhanDouRpcMoveAsk() {
  SharedDtor();
}

void ZhanDouRpcMoveAsk::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ZhanDouRpcMoveAsk::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZhanDouRpcMoveAsk::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZhanDouRpcMoveAsk_descriptor_;
}

const ZhanDouRpcMoveAsk& ZhanDouRpcMoveAsk::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ZhanDouRpc_2eproto();
  return *default_instance_;
}

ZhanDouRpcMoveAsk* ZhanDouRpcMoveAsk::default_instance_ = NULL;

ZhanDouRpcMoveAsk* ZhanDouRpcMoveAsk::New() const {
  return new ZhanDouRpcMoveAsk;
}

void ZhanDouRpcMoveAsk::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ZhanDouRpcMoveAsk::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void ZhanDouRpcMoveAsk::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ZhanDouRpcMoveAsk::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ZhanDouRpcMoveAsk::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZhanDouRpcMoveAsk::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ZhanDouRpcMoveAsk* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ZhanDouRpcMoveAsk*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ZhanDouRpcMoveAsk::MergeFrom(const ZhanDouRpcMoveAsk& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ZhanDouRpcMoveAsk::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZhanDouRpcMoveAsk::CopyFrom(const ZhanDouRpcMoveAsk& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZhanDouRpcMoveAsk::IsInitialized() const {

  return true;
}

void ZhanDouRpcMoveAsk::Swap(ZhanDouRpcMoveAsk* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ZhanDouRpcMoveAsk::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZhanDouRpcMoveAsk_descriptor_;
  metadata.reflection = ZhanDouRpcMoveAsk_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ZhanDouRpcMoveReply::kResultFieldNumber;
#endif  // !_MSC_VER

ZhanDouRpcMoveReply::ZhanDouRpcMoveReply()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ZhanDouRpcMoveReply::InitAsDefaultInstance() {
}

ZhanDouRpcMoveReply::ZhanDouRpcMoveReply(const ZhanDouRpcMoveReply& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ZhanDouRpcMoveReply::SharedCtor() {
  _cached_size_ = 0;
  result_ = -9999;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ZhanDouRpcMoveReply::~ZhanDouRpcMoveReply() {
  SharedDtor();
}

void ZhanDouRpcMoveReply::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ZhanDouRpcMoveReply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZhanDouRpcMoveReply::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZhanDouRpcMoveReply_descriptor_;
}

const ZhanDouRpcMoveReply& ZhanDouRpcMoveReply::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ZhanDouRpc_2eproto();
  return *default_instance_;
}

ZhanDouRpcMoveReply* ZhanDouRpcMoveReply::default_instance_ = NULL;

ZhanDouRpcMoveReply* ZhanDouRpcMoveReply::New() const {
  return new ZhanDouRpcMoveReply;
}

void ZhanDouRpcMoveReply::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    result_ = -9999;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ZhanDouRpcMoveReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional sint32 Result = 1 [default = -9999];
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &result_)));
          set_has_result();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void ZhanDouRpcMoveReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional sint32 Result = 1 [default = -9999];
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->result(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ZhanDouRpcMoveReply::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional sint32 Result = 1 [default = -9999];
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(1, this->result(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ZhanDouRpcMoveReply::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional sint32 Result = 1 [default = -9999];
    if (has_result()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->result());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZhanDouRpcMoveReply::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ZhanDouRpcMoveReply* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ZhanDouRpcMoveReply*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ZhanDouRpcMoveReply::MergeFrom(const ZhanDouRpcMoveReply& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_result()) {
      set_result(from.result());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ZhanDouRpcMoveReply::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZhanDouRpcMoveReply::CopyFrom(const ZhanDouRpcMoveReply& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZhanDouRpcMoveReply::IsInitialized() const {

  return true;
}

void ZhanDouRpcMoveReply::Swap(ZhanDouRpcMoveReply* other) {
  if (other != this) {
    std::swap(result_, other->result_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ZhanDouRpcMoveReply::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZhanDouRpcMoveReply_descriptor_;
  metadata.reflection = ZhanDouRpcMoveReply_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

ZhanDouRpcTalkNotify::ZhanDouRpcTalkNotify()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void ZhanDouRpcTalkNotify::InitAsDefaultInstance() {
}

ZhanDouRpcTalkNotify::ZhanDouRpcTalkNotify(const ZhanDouRpcTalkNotify& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void ZhanDouRpcTalkNotify::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ZhanDouRpcTalkNotify::~ZhanDouRpcTalkNotify() {
  SharedDtor();
}

void ZhanDouRpcTalkNotify::SharedDtor() {
  if (this != default_instance_) {
  }
}

void ZhanDouRpcTalkNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZhanDouRpcTalkNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ZhanDouRpcTalkNotify_descriptor_;
}

const ZhanDouRpcTalkNotify& ZhanDouRpcTalkNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ZhanDouRpc_2eproto();
  return *default_instance_;
}

ZhanDouRpcTalkNotify* ZhanDouRpcTalkNotify::default_instance_ = NULL;

ZhanDouRpcTalkNotify* ZhanDouRpcTalkNotify::New() const {
  return new ZhanDouRpcTalkNotify;
}

void ZhanDouRpcTalkNotify::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ZhanDouRpcTalkNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void ZhanDouRpcTalkNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* ZhanDouRpcTalkNotify::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int ZhanDouRpcTalkNotify::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ZhanDouRpcTalkNotify::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ZhanDouRpcTalkNotify* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ZhanDouRpcTalkNotify*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ZhanDouRpcTalkNotify::MergeFrom(const ZhanDouRpcTalkNotify& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ZhanDouRpcTalkNotify::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ZhanDouRpcTalkNotify::CopyFrom(const ZhanDouRpcTalkNotify& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ZhanDouRpcTalkNotify::IsInitialized() const {

  return true;
}

void ZhanDouRpcTalkNotify::Swap(ZhanDouRpcTalkNotify* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ZhanDouRpcTalkNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ZhanDouRpcTalkNotify_descriptor_;
  metadata.reflection = ZhanDouRpcTalkNotify_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
