// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AchievementV1Data.proto

#ifndef PROTOBUF_AchievementV1Data_2eproto__INCLUDED
#define PROTOBUF_AchievementV1Data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PublicStruct.pb.h"
// @@protoc_insertion_point(includes)
class AchievementAchiDataV1;
class AchievementAchiDataV1DefaultTypeInternal;
extern AchievementAchiDataV1DefaultTypeInternal _AchievementAchiDataV1_default_instance_;
class AchievementAchiObjV1;
class AchievementAchiObjV1DefaultTypeInternal;
extern AchievementAchiObjV1DefaultTypeInternal _AchievementAchiObjV1_default_instance_;

namespace protobuf_AchievementV1Data_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_AchievementV1Data_2eproto

// ===================================================================

class AchievementAchiObjV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AchievementAchiObjV1) */ {
 public:
  AchievementAchiObjV1();
  virtual ~AchievementAchiObjV1();

  AchievementAchiObjV1(const AchievementAchiObjV1& from);

  inline AchievementAchiObjV1& operator=(const AchievementAchiObjV1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AchievementAchiObjV1(AchievementAchiObjV1&& from) noexcept
    : AchievementAchiObjV1() {
    *this = ::std::move(from);
  }

  inline AchievementAchiObjV1& operator=(AchievementAchiObjV1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AchievementAchiObjV1& default_instance();

  static inline const AchievementAchiObjV1* internal_default_instance() {
    return reinterpret_cast<const AchievementAchiObjV1*>(
               &_AchievementAchiObjV1_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(AchievementAchiObjV1* other);
  friend void swap(AchievementAchiObjV1& a, AchievementAchiObjV1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AchievementAchiObjV1* New() const PROTOBUF_FINAL { return New(NULL); }

  AchievementAchiObjV1* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AchievementAchiObjV1& from);
  void MergeFrom(const AchievementAchiObjV1& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AchievementAchiObjV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Type = 6 [default = -1];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 6;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // optional sint32 GroupId = 1 [default = -1];
  bool has_groupid() const;
  void clear_groupid();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::int32 groupid() const;
  void set_groupid(::google::protobuf::int32 value);

  // optional sint32 Star = 3 [default = -1];
  bool has_star() const;
  void clear_star();
  static const int kStarFieldNumber = 3;
  ::google::protobuf::int32 star() const;
  void set_star(::google::protobuf::int32 value);

  // optional sint32 Status = 4 [default = -1];
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  ::google::protobuf::int32 status() const;
  void set_status(::google::protobuf::int32 value);

  // optional sint32 Id = 5 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 5;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:AchievementAchiObjV1)
 private:
  void set_has_groupid();
  void clear_has_groupid();
  void set_has_star();
  void clear_has_star();
  void set_has_status();
  void clear_has_status();
  void set_has_id();
  void clear_has_id();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 type_;
  ::google::protobuf::int32 groupid_;
  ::google::protobuf::int32 star_;
  ::google::protobuf::int32 status_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_AchievementV1Data_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AchievementAchiDataV1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AchievementAchiDataV1) */ {
 public:
  AchievementAchiDataV1();
  virtual ~AchievementAchiDataV1();

  AchievementAchiDataV1(const AchievementAchiDataV1& from);

  inline AchievementAchiDataV1& operator=(const AchievementAchiDataV1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AchievementAchiDataV1(AchievementAchiDataV1&& from) noexcept
    : AchievementAchiDataV1() {
    *this = ::std::move(from);
  }

  inline AchievementAchiDataV1& operator=(AchievementAchiDataV1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AchievementAchiDataV1& default_instance();

  static inline const AchievementAchiDataV1* internal_default_instance() {
    return reinterpret_cast<const AchievementAchiDataV1*>(
               &_AchievementAchiDataV1_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AchievementAchiDataV1* other);
  friend void swap(AchievementAchiDataV1& a, AchievementAchiDataV1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AchievementAchiDataV1* New() const PROTOBUF_FINAL { return New(NULL); }

  AchievementAchiDataV1* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AchievementAchiDataV1& from);
  void MergeFrom(const AchievementAchiDataV1& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AchievementAchiDataV1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .AchievementAchiObjV1 AchiData = 1;
  int achidata_size() const;
  void clear_achidata();
  static const int kAchiDataFieldNumber = 1;
  const ::AchievementAchiObjV1& achidata(int index) const;
  ::AchievementAchiObjV1* mutable_achidata(int index);
  ::AchievementAchiObjV1* add_achidata();
  ::google::protobuf::RepeatedPtrField< ::AchievementAchiObjV1 >*
      mutable_achidata();
  const ::google::protobuf::RepeatedPtrField< ::AchievementAchiObjV1 >&
      achidata() const;

  // @@protoc_insertion_point(class_scope:AchievementAchiDataV1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::AchievementAchiObjV1 > achidata_;
  friend struct protobuf_AchievementV1Data_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AchievementAchiObjV1

// optional sint32 GroupId = 1 [default = -1];
inline bool AchievementAchiObjV1::has_groupid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AchievementAchiObjV1::set_has_groupid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AchievementAchiObjV1::clear_has_groupid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AchievementAchiObjV1::clear_groupid() {
  groupid_ = -1;
  clear_has_groupid();
}
inline ::google::protobuf::int32 AchievementAchiObjV1::groupid() const {
  // @@protoc_insertion_point(field_get:AchievementAchiObjV1.GroupId)
  return groupid_;
}
inline void AchievementAchiObjV1::set_groupid(::google::protobuf::int32 value) {
  set_has_groupid();
  groupid_ = value;
  // @@protoc_insertion_point(field_set:AchievementAchiObjV1.GroupId)
}

// optional sint32 Star = 3 [default = -1];
inline bool AchievementAchiObjV1::has_star() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AchievementAchiObjV1::set_has_star() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AchievementAchiObjV1::clear_has_star() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AchievementAchiObjV1::clear_star() {
  star_ = -1;
  clear_has_star();
}
inline ::google::protobuf::int32 AchievementAchiObjV1::star() const {
  // @@protoc_insertion_point(field_get:AchievementAchiObjV1.Star)
  return star_;
}
inline void AchievementAchiObjV1::set_star(::google::protobuf::int32 value) {
  set_has_star();
  star_ = value;
  // @@protoc_insertion_point(field_set:AchievementAchiObjV1.Star)
}

// optional sint32 Status = 4 [default = -1];
inline bool AchievementAchiObjV1::has_status() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void AchievementAchiObjV1::set_has_status() {
  _has_bits_[0] |= 0x00000008u;
}
inline void AchievementAchiObjV1::clear_has_status() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void AchievementAchiObjV1::clear_status() {
  status_ = -1;
  clear_has_status();
}
inline ::google::protobuf::int32 AchievementAchiObjV1::status() const {
  // @@protoc_insertion_point(field_get:AchievementAchiObjV1.Status)
  return status_;
}
inline void AchievementAchiObjV1::set_status(::google::protobuf::int32 value) {
  set_has_status();
  status_ = value;
  // @@protoc_insertion_point(field_set:AchievementAchiObjV1.Status)
}

// optional sint32 Id = 5 [default = -1];
inline bool AchievementAchiObjV1::has_id() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void AchievementAchiObjV1::set_has_id() {
  _has_bits_[0] |= 0x00000010u;
}
inline void AchievementAchiObjV1::clear_has_id() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void AchievementAchiObjV1::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 AchievementAchiObjV1::id() const {
  // @@protoc_insertion_point(field_get:AchievementAchiObjV1.Id)
  return id_;
}
inline void AchievementAchiObjV1::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:AchievementAchiObjV1.Id)
}

// optional sint32 Type = 6 [default = -1];
inline bool AchievementAchiObjV1::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AchievementAchiObjV1::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AchievementAchiObjV1::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AchievementAchiObjV1::clear_type() {
  type_ = -1;
  clear_has_type();
}
inline ::google::protobuf::int32 AchievementAchiObjV1::type() const {
  // @@protoc_insertion_point(field_get:AchievementAchiObjV1.Type)
  return type_;
}
inline void AchievementAchiObjV1::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:AchievementAchiObjV1.Type)
}

// -------------------------------------------------------------------

// AchievementAchiDataV1

// repeated .AchievementAchiObjV1 AchiData = 1;
inline int AchievementAchiDataV1::achidata_size() const {
  return achidata_.size();
}
inline void AchievementAchiDataV1::clear_achidata() {
  achidata_.Clear();
}
inline const ::AchievementAchiObjV1& AchievementAchiDataV1::achidata(int index) const {
  // @@protoc_insertion_point(field_get:AchievementAchiDataV1.AchiData)
  return achidata_.Get(index);
}
inline ::AchievementAchiObjV1* AchievementAchiDataV1::mutable_achidata(int index) {
  // @@protoc_insertion_point(field_mutable:AchievementAchiDataV1.AchiData)
  return achidata_.Mutable(index);
}
inline ::AchievementAchiObjV1* AchievementAchiDataV1::add_achidata() {
  // @@protoc_insertion_point(field_add:AchievementAchiDataV1.AchiData)
  return achidata_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::AchievementAchiObjV1 >*
AchievementAchiDataV1::mutable_achidata() {
  // @@protoc_insertion_point(field_mutable_list:AchievementAchiDataV1.AchiData)
  return &achidata_;
}
inline const ::google::protobuf::RepeatedPtrField< ::AchievementAchiObjV1 >&
AchievementAchiDataV1::achidata() const {
  // @@protoc_insertion_point(field_list:AchievementAchiDataV1.AchiData)
  return achidata_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_AchievementV1Data_2eproto__INCLUDED
