// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TalismanRpc.proto

#ifndef PROTOBUF_TalismanRpc_2eproto__INCLUDED
#define PROTOBUF_TalismanRpc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PublicStruct.pb.h"
// @@protoc_insertion_point(includes)
class TalismanRpcActiveAsk;
class TalismanRpcActiveAskDefaultTypeInternal;
extern TalismanRpcActiveAskDefaultTypeInternal _TalismanRpcActiveAsk_default_instance_;
class TalismanRpcActiveReply;
class TalismanRpcActiveReplyDefaultTypeInternal;
extern TalismanRpcActiveReplyDefaultTypeInternal _TalismanRpcActiveReply_default_instance_;
class TalismanRpcSyncDataAsk;
class TalismanRpcSyncDataAskDefaultTypeInternal;
extern TalismanRpcSyncDataAskDefaultTypeInternal _TalismanRpcSyncDataAsk_default_instance_;
class TalismanRpcSyncDataReply;
class TalismanRpcSyncDataReplyDefaultTypeInternal;
extern TalismanRpcSyncDataReplyDefaultTypeInternal _TalismanRpcSyncDataReply_default_instance_;
class TalismanRpcUpgradeAsk;
class TalismanRpcUpgradeAskDefaultTypeInternal;
extern TalismanRpcUpgradeAskDefaultTypeInternal _TalismanRpcUpgradeAsk_default_instance_;
class TalismanRpcUpgradeReply;
class TalismanRpcUpgradeReplyDefaultTypeInternal;
extern TalismanRpcUpgradeReplyDefaultTypeInternal _TalismanRpcUpgradeReply_default_instance_;

namespace protobuf_TalismanRpc_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_TalismanRpc_2eproto

// ===================================================================

class TalismanRpcSyncDataAsk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcSyncDataAsk) */ {
 public:
  TalismanRpcSyncDataAsk();
  virtual ~TalismanRpcSyncDataAsk();

  TalismanRpcSyncDataAsk(const TalismanRpcSyncDataAsk& from);

  inline TalismanRpcSyncDataAsk& operator=(const TalismanRpcSyncDataAsk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcSyncDataAsk(TalismanRpcSyncDataAsk&& from) noexcept
    : TalismanRpcSyncDataAsk() {
    *this = ::std::move(from);
  }

  inline TalismanRpcSyncDataAsk& operator=(TalismanRpcSyncDataAsk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcSyncDataAsk& default_instance();

  static inline const TalismanRpcSyncDataAsk* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcSyncDataAsk*>(
               &_TalismanRpcSyncDataAsk_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TalismanRpcSyncDataAsk* other);
  friend void swap(TalismanRpcSyncDataAsk& a, TalismanRpcSyncDataAsk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcSyncDataAsk* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcSyncDataAsk* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcSyncDataAsk& from);
  void MergeFrom(const TalismanRpcSyncDataAsk& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcSyncDataAsk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:TalismanRpcSyncDataAsk)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TalismanRpcSyncDataReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcSyncDataReply) */ {
 public:
  TalismanRpcSyncDataReply();
  virtual ~TalismanRpcSyncDataReply();

  TalismanRpcSyncDataReply(const TalismanRpcSyncDataReply& from);

  inline TalismanRpcSyncDataReply& operator=(const TalismanRpcSyncDataReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcSyncDataReply(TalismanRpcSyncDataReply&& from) noexcept
    : TalismanRpcSyncDataReply() {
    *this = ::std::move(from);
  }

  inline TalismanRpcSyncDataReply& operator=(TalismanRpcSyncDataReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcSyncDataReply& default_instance();

  static inline const TalismanRpcSyncDataReply* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcSyncDataReply*>(
               &_TalismanRpcSyncDataReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(TalismanRpcSyncDataReply* other);
  friend void swap(TalismanRpcSyncDataReply& a, TalismanRpcSyncDataReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcSyncDataReply* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcSyncDataReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcSyncDataReply& from);
  void MergeFrom(const TalismanRpcSyncDataReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcSyncDataReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Result = 1 [default = -9999];
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TalismanRpcSyncDataReply)
 private:
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TalismanRpcUpgradeAsk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcUpgradeAsk) */ {
 public:
  TalismanRpcUpgradeAsk();
  virtual ~TalismanRpcUpgradeAsk();

  TalismanRpcUpgradeAsk(const TalismanRpcUpgradeAsk& from);

  inline TalismanRpcUpgradeAsk& operator=(const TalismanRpcUpgradeAsk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcUpgradeAsk(TalismanRpcUpgradeAsk&& from) noexcept
    : TalismanRpcUpgradeAsk() {
    *this = ::std::move(from);
  }

  inline TalismanRpcUpgradeAsk& operator=(TalismanRpcUpgradeAsk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcUpgradeAsk& default_instance();

  static inline const TalismanRpcUpgradeAsk* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcUpgradeAsk*>(
               &_TalismanRpcUpgradeAsk_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(TalismanRpcUpgradeAsk* other);
  friend void swap(TalismanRpcUpgradeAsk& a, TalismanRpcUpgradeAsk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcUpgradeAsk* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcUpgradeAsk* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcUpgradeAsk& from);
  void MergeFrom(const TalismanRpcUpgradeAsk& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcUpgradeAsk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 ID = 1 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // optional sint32 Type = 3 [default = -1];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 3;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TalismanRpcUpgradeAsk)
 private:
  void set_has_id();
  void clear_has_id();
  void set_has_type();
  void clear_has_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 type_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TalismanRpcUpgradeReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcUpgradeReply) */ {
 public:
  TalismanRpcUpgradeReply();
  virtual ~TalismanRpcUpgradeReply();

  TalismanRpcUpgradeReply(const TalismanRpcUpgradeReply& from);

  inline TalismanRpcUpgradeReply& operator=(const TalismanRpcUpgradeReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcUpgradeReply(TalismanRpcUpgradeReply&& from) noexcept
    : TalismanRpcUpgradeReply() {
    *this = ::std::move(from);
  }

  inline TalismanRpcUpgradeReply& operator=(TalismanRpcUpgradeReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcUpgradeReply& default_instance();

  static inline const TalismanRpcUpgradeReply* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcUpgradeReply*>(
               &_TalismanRpcUpgradeReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(TalismanRpcUpgradeReply* other);
  friend void swap(TalismanRpcUpgradeReply& a, TalismanRpcUpgradeReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcUpgradeReply* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcUpgradeReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcUpgradeReply& from);
  void MergeFrom(const TalismanRpcUpgradeReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcUpgradeReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Result = 1 [default = -9999];
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // optional sint32 ID = 2 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIDFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TalismanRpcUpgradeReply)
 private:
  void set_has_result();
  void clear_has_result();
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TalismanRpcActiveAsk : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcActiveAsk) */ {
 public:
  TalismanRpcActiveAsk();
  virtual ~TalismanRpcActiveAsk();

  TalismanRpcActiveAsk(const TalismanRpcActiveAsk& from);

  inline TalismanRpcActiveAsk& operator=(const TalismanRpcActiveAsk& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcActiveAsk(TalismanRpcActiveAsk&& from) noexcept
    : TalismanRpcActiveAsk() {
    *this = ::std::move(from);
  }

  inline TalismanRpcActiveAsk& operator=(TalismanRpcActiveAsk&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcActiveAsk& default_instance();

  static inline const TalismanRpcActiveAsk* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcActiveAsk*>(
               &_TalismanRpcActiveAsk_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(TalismanRpcActiveAsk* other);
  friend void swap(TalismanRpcActiveAsk& a, TalismanRpcActiveAsk& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcActiveAsk* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcActiveAsk* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcActiveAsk& from);
  void MergeFrom(const TalismanRpcActiveAsk& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcActiveAsk* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 ID = 1 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIDFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TalismanRpcActiveAsk)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TalismanRpcActiveReply : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:TalismanRpcActiveReply) */ {
 public:
  TalismanRpcActiveReply();
  virtual ~TalismanRpcActiveReply();

  TalismanRpcActiveReply(const TalismanRpcActiveReply& from);

  inline TalismanRpcActiveReply& operator=(const TalismanRpcActiveReply& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TalismanRpcActiveReply(TalismanRpcActiveReply&& from) noexcept
    : TalismanRpcActiveReply() {
    *this = ::std::move(from);
  }

  inline TalismanRpcActiveReply& operator=(TalismanRpcActiveReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TalismanRpcActiveReply& default_instance();

  static inline const TalismanRpcActiveReply* internal_default_instance() {
    return reinterpret_cast<const TalismanRpcActiveReply*>(
               &_TalismanRpcActiveReply_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(TalismanRpcActiveReply* other);
  friend void swap(TalismanRpcActiveReply& a, TalismanRpcActiveReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TalismanRpcActiveReply* New() const PROTOBUF_FINAL { return New(NULL); }

  TalismanRpcActiveReply* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TalismanRpcActiveReply& from);
  void MergeFrom(const TalismanRpcActiveReply& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TalismanRpcActiveReply* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Result = 1 [default = -9999];
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // optional sint32 ID = 2 [default = -1];
  bool has_id() const;
  void clear_id();
  static const int kIDFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TalismanRpcActiveReply)
 private:
  void set_has_result();
  void clear_has_result();
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 id_;
  friend struct protobuf_TalismanRpc_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TalismanRpcSyncDataAsk

// -------------------------------------------------------------------

// TalismanRpcSyncDataReply

// optional sint32 Result = 1 [default = -9999];
inline bool TalismanRpcSyncDataReply::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalismanRpcSyncDataReply::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalismanRpcSyncDataReply::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalismanRpcSyncDataReply::clear_result() {
  result_ = -9999;
  clear_has_result();
}
inline ::google::protobuf::int32 TalismanRpcSyncDataReply::result() const {
  // @@protoc_insertion_point(field_get:TalismanRpcSyncDataReply.Result)
  return result_;
}
inline void TalismanRpcSyncDataReply::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcSyncDataReply.Result)
}

// -------------------------------------------------------------------

// TalismanRpcUpgradeAsk

// optional sint32 ID = 1 [default = -1];
inline bool TalismanRpcUpgradeAsk::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalismanRpcUpgradeAsk::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalismanRpcUpgradeAsk::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalismanRpcUpgradeAsk::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 TalismanRpcUpgradeAsk::id() const {
  // @@protoc_insertion_point(field_get:TalismanRpcUpgradeAsk.ID)
  return id_;
}
inline void TalismanRpcUpgradeAsk::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcUpgradeAsk.ID)
}

// optional sint32 Type = 3 [default = -1];
inline bool TalismanRpcUpgradeAsk::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TalismanRpcUpgradeAsk::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TalismanRpcUpgradeAsk::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TalismanRpcUpgradeAsk::clear_type() {
  type_ = -1;
  clear_has_type();
}
inline ::google::protobuf::int32 TalismanRpcUpgradeAsk::type() const {
  // @@protoc_insertion_point(field_get:TalismanRpcUpgradeAsk.Type)
  return type_;
}
inline void TalismanRpcUpgradeAsk::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcUpgradeAsk.Type)
}

// -------------------------------------------------------------------

// TalismanRpcUpgradeReply

// optional sint32 Result = 1 [default = -9999];
inline bool TalismanRpcUpgradeReply::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalismanRpcUpgradeReply::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalismanRpcUpgradeReply::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalismanRpcUpgradeReply::clear_result() {
  result_ = -9999;
  clear_has_result();
}
inline ::google::protobuf::int32 TalismanRpcUpgradeReply::result() const {
  // @@protoc_insertion_point(field_get:TalismanRpcUpgradeReply.Result)
  return result_;
}
inline void TalismanRpcUpgradeReply::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcUpgradeReply.Result)
}

// optional sint32 ID = 2 [default = -1];
inline bool TalismanRpcUpgradeReply::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TalismanRpcUpgradeReply::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TalismanRpcUpgradeReply::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TalismanRpcUpgradeReply::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 TalismanRpcUpgradeReply::id() const {
  // @@protoc_insertion_point(field_get:TalismanRpcUpgradeReply.ID)
  return id_;
}
inline void TalismanRpcUpgradeReply::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcUpgradeReply.ID)
}

// -------------------------------------------------------------------

// TalismanRpcActiveAsk

// optional sint32 ID = 1 [default = -1];
inline bool TalismanRpcActiveAsk::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalismanRpcActiveAsk::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalismanRpcActiveAsk::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalismanRpcActiveAsk::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 TalismanRpcActiveAsk::id() const {
  // @@protoc_insertion_point(field_get:TalismanRpcActiveAsk.ID)
  return id_;
}
inline void TalismanRpcActiveAsk::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcActiveAsk.ID)
}

// -------------------------------------------------------------------

// TalismanRpcActiveReply

// optional sint32 Result = 1 [default = -9999];
inline bool TalismanRpcActiveReply::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TalismanRpcActiveReply::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TalismanRpcActiveReply::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TalismanRpcActiveReply::clear_result() {
  result_ = -9999;
  clear_has_result();
}
inline ::google::protobuf::int32 TalismanRpcActiveReply::result() const {
  // @@protoc_insertion_point(field_get:TalismanRpcActiveReply.Result)
  return result_;
}
inline void TalismanRpcActiveReply::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcActiveReply.Result)
}

// optional sint32 ID = 2 [default = -1];
inline bool TalismanRpcActiveReply::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TalismanRpcActiveReply::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TalismanRpcActiveReply::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TalismanRpcActiveReply::clear_id() {
  id_ = -1;
  clear_has_id();
}
inline ::google::protobuf::int32 TalismanRpcActiveReply::id() const {
  // @@protoc_insertion_point(field_get:TalismanRpcActiveReply.ID)
  return id_;
}
inline void TalismanRpcActiveReply::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:TalismanRpcActiveReply.ID)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TalismanRpc_2eproto__INCLUDED
