// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineDataV1Data.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "OnlineDataV1Data.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class OnlineDataOnlineDataV1DefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<OnlineDataOnlineDataV1>
     _instance;
} _OnlineDataOnlineDataV1_default_instance_;
class OnlineDataRoleAttrObjV1DefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<OnlineDataRoleAttrObjV1>
     _instance;
} _OnlineDataRoleAttrObjV1_default_instance_;

namespace protobuf_OnlineDataV1Data_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, bagrecyclebin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, roleattr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, recommendfriendoffset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, recommendfriendflushtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, recommendfriendlastlist_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, followmeuserid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, followwho_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataOnlineDataV1, thiefobjid_),
  ~0u,
  ~0u,
  0,
  1,
  ~0u,
  ~0u,
  2,
  3,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataRoleAttrObjV1, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataRoleAttrObjV1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataRoleAttrObjV1, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OnlineDataRoleAttrObjV1, value_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 13, sizeof(OnlineDataOnlineDataV1)},
  { 21, 28, sizeof(OnlineDataRoleAttrObjV1)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_OnlineDataOnlineDataV1_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_OnlineDataRoleAttrObjV1_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "OnlineDataV1Data.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::protobuf_PublicStruct_2eproto::InitDefaults();
  _OnlineDataOnlineDataV1_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_OnlineDataOnlineDataV1_default_instance_);_OnlineDataRoleAttrObjV1_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_OnlineDataRoleAttrObjV1_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026OnlineDataV1Data.proto\032\022PublicStruct.p"
      "roto\"\237\002\n\026OnlineDataOnlineDataV1\022)\n\rBagRe"
      "cycleBin\030\001 \003(\0132\022.BagRecycleGridObj\022*\n\010Ro"
      "leAttr\030\002 \003(\0132\030.OnlineDataRoleAttrObjV1\022 "
      "\n\025RecommendFriendOffset\030\004 \001(\021:\0010\022$\n\030Reco"
      "mmendFriendFlushTime\030\005 \001(\021:\002-1\022\037\n\027Recomm"
      "endFriendLastList\030\006 \003(\022\022\026\n\016FollowmeUserI"
      "d\030\007 \003(\022\022\025\n\tFollowWho\030\t \001(\022:\002-1\022\026\n\nThiefO"
      "bjId\030\n \001(\022:\002-1\"<\n\027OnlineDataRoleAttrObjV"
      "1\022\016\n\002Id\030\001 \001(\021:\002-1\022\021\n\005Value\030\002 \001(\002:\002-1"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 396);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "OnlineDataV1Data.proto", &protobuf_RegisterTypes);
  ::protobuf_PublicStruct_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_OnlineDataV1Data_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OnlineDataOnlineDataV1::kBagRecycleBinFieldNumber;
const int OnlineDataOnlineDataV1::kRoleAttrFieldNumber;
const int OnlineDataOnlineDataV1::kRecommendFriendOffsetFieldNumber;
const int OnlineDataOnlineDataV1::kRecommendFriendFlushTimeFieldNumber;
const int OnlineDataOnlineDataV1::kRecommendFriendLastListFieldNumber;
const int OnlineDataOnlineDataV1::kFollowmeUserIdFieldNumber;
const int OnlineDataOnlineDataV1::kFollowWhoFieldNumber;
const int OnlineDataOnlineDataV1::kThiefObjIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OnlineDataOnlineDataV1::OnlineDataOnlineDataV1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_OnlineDataV1Data_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OnlineDataOnlineDataV1)
}
OnlineDataOnlineDataV1::OnlineDataOnlineDataV1(const OnlineDataOnlineDataV1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      bagrecyclebin_(from.bagrecyclebin_),
      roleattr_(from.roleattr_),
      recommendfriendlastlist_(from.recommendfriendlastlist_),
      followmeuserid_(from.followmeuserid_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&recommendfriendoffset_, &from.recommendfriendoffset_,
    static_cast<size_t>(reinterpret_cast<char*>(&thiefobjid_) -
    reinterpret_cast<char*>(&recommendfriendoffset_)) + sizeof(thiefobjid_));
  // @@protoc_insertion_point(copy_constructor:OnlineDataOnlineDataV1)
}

void OnlineDataOnlineDataV1::SharedCtor() {
  _cached_size_ = 0;
  recommendfriendoffset_ = 0;
  recommendfriendflushtime_ = -1;
  followwho_ = GOOGLE_LONGLONG(-1);
  thiefobjid_ = GOOGLE_LONGLONG(-1);
}

OnlineDataOnlineDataV1::~OnlineDataOnlineDataV1() {
  // @@protoc_insertion_point(destructor:OnlineDataOnlineDataV1)
  SharedDtor();
}

void OnlineDataOnlineDataV1::SharedDtor() {
}

void OnlineDataOnlineDataV1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OnlineDataOnlineDataV1::descriptor() {
  protobuf_OnlineDataV1Data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OnlineDataV1Data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OnlineDataOnlineDataV1& OnlineDataOnlineDataV1::default_instance() {
  protobuf_OnlineDataV1Data_2eproto::InitDefaults();
  return *internal_default_instance();
}

OnlineDataOnlineDataV1* OnlineDataOnlineDataV1::New(::google::protobuf::Arena* arena) const {
  OnlineDataOnlineDataV1* n = new OnlineDataOnlineDataV1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OnlineDataOnlineDataV1::Clear() {
// @@protoc_insertion_point(message_clear_start:OnlineDataOnlineDataV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bagrecyclebin_.Clear();
  roleattr_.Clear();
  recommendfriendlastlist_.Clear();
  followmeuserid_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 15u) {
    recommendfriendoffset_ = 0;
    recommendfriendflushtime_ = -1;
    followwho_ = GOOGLE_LONGLONG(-1);
    thiefobjid_ = GOOGLE_LONGLONG(-1);
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool OnlineDataOnlineDataV1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OnlineDataOnlineDataV1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .BagRecycleGridObj BagRecycleBin = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_bagrecyclebin()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .OnlineDataRoleAttrObjV1 RoleAttr = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_roleattr()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional sint32 RecommendFriendOffset = 4 [default = 0];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_recommendfriendoffset();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &recommendfriendoffset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional sint32 RecommendFriendFlushTime = 5 [default = -1];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_recommendfriendflushtime();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &recommendfriendflushtime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated sint64 RecommendFriendLastList = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 1, 48u, input, this->mutable_recommendfriendlastlist())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, this->mutable_recommendfriendlastlist())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated sint64 FollowmeUserId = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 1, 56u, input, this->mutable_followmeuserid())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, this->mutable_followmeuserid())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional sint64 FollowWho = 9 [default = -1];
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          set_has_followwho();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &followwho_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional sint64 ThiefObjId = 10 [default = -1];
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {
          set_has_thiefobjid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SINT64>(
                 input, &thiefobjid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OnlineDataOnlineDataV1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OnlineDataOnlineDataV1)
  return false;
#undef DO_
}

void OnlineDataOnlineDataV1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OnlineDataOnlineDataV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BagRecycleGridObj BagRecycleBin = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bagrecyclebin_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->bagrecyclebin(static_cast<int>(i)), output);
  }

  // repeated .OnlineDataRoleAttrObjV1 RoleAttr = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->roleattr_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->roleattr(static_cast<int>(i)), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional sint32 RecommendFriendOffset = 4 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(4, this->recommendfriendoffset(), output);
  }

  // optional sint32 RecommendFriendFlushTime = 5 [default = -1];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(5, this->recommendfriendflushtime(), output);
  }

  // repeated sint64 RecommendFriendLastList = 6;
  for (int i = 0, n = this->recommendfriendlastlist_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(
      6, this->recommendfriendlastlist(i), output);
  }

  // repeated sint64 FollowmeUserId = 7;
  for (int i = 0, n = this->followmeuserid_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(
      7, this->followmeuserid(i), output);
  }

  // optional sint64 FollowWho = 9 [default = -1];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(9, this->followwho(), output);
  }

  // optional sint64 ThiefObjId = 10 [default = -1];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt64(10, this->thiefobjid(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:OnlineDataOnlineDataV1)
}

::google::protobuf::uint8* OnlineDataOnlineDataV1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OnlineDataOnlineDataV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .BagRecycleGridObj BagRecycleBin = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bagrecyclebin_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->bagrecyclebin(static_cast<int>(i)), deterministic, target);
  }

  // repeated .OnlineDataRoleAttrObjV1 RoleAttr = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->roleattr_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->roleattr(static_cast<int>(i)), deterministic, target);
  }

  cached_has_bits = _has_bits_[0];
  // optional sint32 RecommendFriendOffset = 4 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(4, this->recommendfriendoffset(), target);
  }

  // optional sint32 RecommendFriendFlushTime = 5 [default = -1];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(5, this->recommendfriendflushtime(), target);
  }

  // repeated sint64 RecommendFriendLastList = 6;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteSInt64ToArray(6, this->recommendfriendlastlist_, target);

  // repeated sint64 FollowmeUserId = 7;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteSInt64ToArray(7, this->followmeuserid_, target);

  // optional sint64 FollowWho = 9 [default = -1];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(9, this->followwho(), target);
  }

  // optional sint64 ThiefObjId = 10 [default = -1];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt64ToArray(10, this->thiefobjid(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OnlineDataOnlineDataV1)
  return target;
}

size_t OnlineDataOnlineDataV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OnlineDataOnlineDataV1)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .BagRecycleGridObj BagRecycleBin = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->bagrecyclebin_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->bagrecyclebin(static_cast<int>(i)));
    }
  }

  // repeated .OnlineDataRoleAttrObjV1 RoleAttr = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->roleattr_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->roleattr(static_cast<int>(i)));
    }
  }

  // repeated sint64 RecommendFriendLastList = 6;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      SInt64Size(this->recommendfriendlastlist_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->recommendfriendlastlist_size());
    total_size += data_size;
  }

  // repeated sint64 FollowmeUserId = 7;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      SInt64Size(this->followmeuserid_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->followmeuserid_size());
    total_size += data_size;
  }

  if (_has_bits_[0 / 32] & 15u) {
    // optional sint32 RecommendFriendOffset = 4 [default = 0];
    if (has_recommendfriendoffset()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->recommendfriendoffset());
    }

    // optional sint32 RecommendFriendFlushTime = 5 [default = -1];
    if (has_recommendfriendflushtime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->recommendfriendflushtime());
    }

    // optional sint64 FollowWho = 9 [default = -1];
    if (has_followwho()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt64Size(
          this->followwho());
    }

    // optional sint64 ThiefObjId = 10 [default = -1];
    if (has_thiefobjid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt64Size(
          this->thiefobjid());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OnlineDataOnlineDataV1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OnlineDataOnlineDataV1)
  GOOGLE_DCHECK_NE(&from, this);
  const OnlineDataOnlineDataV1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OnlineDataOnlineDataV1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OnlineDataOnlineDataV1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OnlineDataOnlineDataV1)
    MergeFrom(*source);
  }
}

void OnlineDataOnlineDataV1::MergeFrom(const OnlineDataOnlineDataV1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OnlineDataOnlineDataV1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bagrecyclebin_.MergeFrom(from.bagrecyclebin_);
  roleattr_.MergeFrom(from.roleattr_);
  recommendfriendlastlist_.MergeFrom(from.recommendfriendlastlist_);
  followmeuserid_.MergeFrom(from.followmeuserid_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 15u) {
    if (cached_has_bits & 0x00000001u) {
      recommendfriendoffset_ = from.recommendfriendoffset_;
    }
    if (cached_has_bits & 0x00000002u) {
      recommendfriendflushtime_ = from.recommendfriendflushtime_;
    }
    if (cached_has_bits & 0x00000004u) {
      followwho_ = from.followwho_;
    }
    if (cached_has_bits & 0x00000008u) {
      thiefobjid_ = from.thiefobjid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OnlineDataOnlineDataV1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OnlineDataOnlineDataV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnlineDataOnlineDataV1::CopyFrom(const OnlineDataOnlineDataV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OnlineDataOnlineDataV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnlineDataOnlineDataV1::IsInitialized() const {
  return true;
}

void OnlineDataOnlineDataV1::Swap(OnlineDataOnlineDataV1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OnlineDataOnlineDataV1::InternalSwap(OnlineDataOnlineDataV1* other) {
  using std::swap;
  bagrecyclebin_.InternalSwap(&other->bagrecyclebin_);
  roleattr_.InternalSwap(&other->roleattr_);
  recommendfriendlastlist_.InternalSwap(&other->recommendfriendlastlist_);
  followmeuserid_.InternalSwap(&other->followmeuserid_);
  swap(recommendfriendoffset_, other->recommendfriendoffset_);
  swap(recommendfriendflushtime_, other->recommendfriendflushtime_);
  swap(followwho_, other->followwho_);
  swap(thiefobjid_, other->thiefobjid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OnlineDataOnlineDataV1::GetMetadata() const {
  protobuf_OnlineDataV1Data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OnlineDataV1Data_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OnlineDataOnlineDataV1

// repeated .BagRecycleGridObj BagRecycleBin = 1;
int OnlineDataOnlineDataV1::bagrecyclebin_size() const {
  return bagrecyclebin_.size();
}
void OnlineDataOnlineDataV1::clear_bagrecyclebin() {
  bagrecyclebin_.Clear();
}
const ::BagRecycleGridObj& OnlineDataOnlineDataV1::bagrecyclebin(int index) const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.BagRecycleBin)
  return bagrecyclebin_.Get(index);
}
::BagRecycleGridObj* OnlineDataOnlineDataV1::mutable_bagrecyclebin(int index) {
  // @@protoc_insertion_point(field_mutable:OnlineDataOnlineDataV1.BagRecycleBin)
  return bagrecyclebin_.Mutable(index);
}
::BagRecycleGridObj* OnlineDataOnlineDataV1::add_bagrecyclebin() {
  // @@protoc_insertion_point(field_add:OnlineDataOnlineDataV1.BagRecycleBin)
  return bagrecyclebin_.Add();
}
::google::protobuf::RepeatedPtrField< ::BagRecycleGridObj >*
OnlineDataOnlineDataV1::mutable_bagrecyclebin() {
  // @@protoc_insertion_point(field_mutable_list:OnlineDataOnlineDataV1.BagRecycleBin)
  return &bagrecyclebin_;
}
const ::google::protobuf::RepeatedPtrField< ::BagRecycleGridObj >&
OnlineDataOnlineDataV1::bagrecyclebin() const {
  // @@protoc_insertion_point(field_list:OnlineDataOnlineDataV1.BagRecycleBin)
  return bagrecyclebin_;
}

// repeated .OnlineDataRoleAttrObjV1 RoleAttr = 2;
int OnlineDataOnlineDataV1::roleattr_size() const {
  return roleattr_.size();
}
void OnlineDataOnlineDataV1::clear_roleattr() {
  roleattr_.Clear();
}
const ::OnlineDataRoleAttrObjV1& OnlineDataOnlineDataV1::roleattr(int index) const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.RoleAttr)
  return roleattr_.Get(index);
}
::OnlineDataRoleAttrObjV1* OnlineDataOnlineDataV1::mutable_roleattr(int index) {
  // @@protoc_insertion_point(field_mutable:OnlineDataOnlineDataV1.RoleAttr)
  return roleattr_.Mutable(index);
}
::OnlineDataRoleAttrObjV1* OnlineDataOnlineDataV1::add_roleattr() {
  // @@protoc_insertion_point(field_add:OnlineDataOnlineDataV1.RoleAttr)
  return roleattr_.Add();
}
::google::protobuf::RepeatedPtrField< ::OnlineDataRoleAttrObjV1 >*
OnlineDataOnlineDataV1::mutable_roleattr() {
  // @@protoc_insertion_point(field_mutable_list:OnlineDataOnlineDataV1.RoleAttr)
  return &roleattr_;
}
const ::google::protobuf::RepeatedPtrField< ::OnlineDataRoleAttrObjV1 >&
OnlineDataOnlineDataV1::roleattr() const {
  // @@protoc_insertion_point(field_list:OnlineDataOnlineDataV1.RoleAttr)
  return roleattr_;
}

// optional sint32 RecommendFriendOffset = 4 [default = 0];
bool OnlineDataOnlineDataV1::has_recommendfriendoffset() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void OnlineDataOnlineDataV1::set_has_recommendfriendoffset() {
  _has_bits_[0] |= 0x00000001u;
}
void OnlineDataOnlineDataV1::clear_has_recommendfriendoffset() {
  _has_bits_[0] &= ~0x00000001u;
}
void OnlineDataOnlineDataV1::clear_recommendfriendoffset() {
  recommendfriendoffset_ = 0;
  clear_has_recommendfriendoffset();
}
::google::protobuf::int32 OnlineDataOnlineDataV1::recommendfriendoffset() const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.RecommendFriendOffset)
  return recommendfriendoffset_;
}
void OnlineDataOnlineDataV1::set_recommendfriendoffset(::google::protobuf::int32 value) {
  set_has_recommendfriendoffset();
  recommendfriendoffset_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.RecommendFriendOffset)
}

// optional sint32 RecommendFriendFlushTime = 5 [default = -1];
bool OnlineDataOnlineDataV1::has_recommendfriendflushtime() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void OnlineDataOnlineDataV1::set_has_recommendfriendflushtime() {
  _has_bits_[0] |= 0x00000002u;
}
void OnlineDataOnlineDataV1::clear_has_recommendfriendflushtime() {
  _has_bits_[0] &= ~0x00000002u;
}
void OnlineDataOnlineDataV1::clear_recommendfriendflushtime() {
  recommendfriendflushtime_ = -1;
  clear_has_recommendfriendflushtime();
}
::google::protobuf::int32 OnlineDataOnlineDataV1::recommendfriendflushtime() const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.RecommendFriendFlushTime)
  return recommendfriendflushtime_;
}
void OnlineDataOnlineDataV1::set_recommendfriendflushtime(::google::protobuf::int32 value) {
  set_has_recommendfriendflushtime();
  recommendfriendflushtime_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.RecommendFriendFlushTime)
}

// repeated sint64 RecommendFriendLastList = 6;
int OnlineDataOnlineDataV1::recommendfriendlastlist_size() const {
  return recommendfriendlastlist_.size();
}
void OnlineDataOnlineDataV1::clear_recommendfriendlastlist() {
  recommendfriendlastlist_.Clear();
}
::google::protobuf::int64 OnlineDataOnlineDataV1::recommendfriendlastlist(int index) const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.RecommendFriendLastList)
  return recommendfriendlastlist_.Get(index);
}
void OnlineDataOnlineDataV1::set_recommendfriendlastlist(int index, ::google::protobuf::int64 value) {
  recommendfriendlastlist_.Set(index, value);
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.RecommendFriendLastList)
}
void OnlineDataOnlineDataV1::add_recommendfriendlastlist(::google::protobuf::int64 value) {
  recommendfriendlastlist_.Add(value);
  // @@protoc_insertion_point(field_add:OnlineDataOnlineDataV1.RecommendFriendLastList)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
OnlineDataOnlineDataV1::recommendfriendlastlist() const {
  // @@protoc_insertion_point(field_list:OnlineDataOnlineDataV1.RecommendFriendLastList)
  return recommendfriendlastlist_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
OnlineDataOnlineDataV1::mutable_recommendfriendlastlist() {
  // @@protoc_insertion_point(field_mutable_list:OnlineDataOnlineDataV1.RecommendFriendLastList)
  return &recommendfriendlastlist_;
}

// repeated sint64 FollowmeUserId = 7;
int OnlineDataOnlineDataV1::followmeuserid_size() const {
  return followmeuserid_.size();
}
void OnlineDataOnlineDataV1::clear_followmeuserid() {
  followmeuserid_.Clear();
}
::google::protobuf::int64 OnlineDataOnlineDataV1::followmeuserid(int index) const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.FollowmeUserId)
  return followmeuserid_.Get(index);
}
void OnlineDataOnlineDataV1::set_followmeuserid(int index, ::google::protobuf::int64 value) {
  followmeuserid_.Set(index, value);
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.FollowmeUserId)
}
void OnlineDataOnlineDataV1::add_followmeuserid(::google::protobuf::int64 value) {
  followmeuserid_.Add(value);
  // @@protoc_insertion_point(field_add:OnlineDataOnlineDataV1.FollowmeUserId)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
OnlineDataOnlineDataV1::followmeuserid() const {
  // @@protoc_insertion_point(field_list:OnlineDataOnlineDataV1.FollowmeUserId)
  return followmeuserid_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
OnlineDataOnlineDataV1::mutable_followmeuserid() {
  // @@protoc_insertion_point(field_mutable_list:OnlineDataOnlineDataV1.FollowmeUserId)
  return &followmeuserid_;
}

// optional sint64 FollowWho = 9 [default = -1];
bool OnlineDataOnlineDataV1::has_followwho() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void OnlineDataOnlineDataV1::set_has_followwho() {
  _has_bits_[0] |= 0x00000004u;
}
void OnlineDataOnlineDataV1::clear_has_followwho() {
  _has_bits_[0] &= ~0x00000004u;
}
void OnlineDataOnlineDataV1::clear_followwho() {
  followwho_ = GOOGLE_LONGLONG(-1);
  clear_has_followwho();
}
::google::protobuf::int64 OnlineDataOnlineDataV1::followwho() const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.FollowWho)
  return followwho_;
}
void OnlineDataOnlineDataV1::set_followwho(::google::protobuf::int64 value) {
  set_has_followwho();
  followwho_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.FollowWho)
}

// optional sint64 ThiefObjId = 10 [default = -1];
bool OnlineDataOnlineDataV1::has_thiefobjid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void OnlineDataOnlineDataV1::set_has_thiefobjid() {
  _has_bits_[0] |= 0x00000008u;
}
void OnlineDataOnlineDataV1::clear_has_thiefobjid() {
  _has_bits_[0] &= ~0x00000008u;
}
void OnlineDataOnlineDataV1::clear_thiefobjid() {
  thiefobjid_ = GOOGLE_LONGLONG(-1);
  clear_has_thiefobjid();
}
::google::protobuf::int64 OnlineDataOnlineDataV1::thiefobjid() const {
  // @@protoc_insertion_point(field_get:OnlineDataOnlineDataV1.ThiefObjId)
  return thiefobjid_;
}
void OnlineDataOnlineDataV1::set_thiefobjid(::google::protobuf::int64 value) {
  set_has_thiefobjid();
  thiefobjid_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataOnlineDataV1.ThiefObjId)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OnlineDataRoleAttrObjV1::kIdFieldNumber;
const int OnlineDataRoleAttrObjV1::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OnlineDataRoleAttrObjV1::OnlineDataRoleAttrObjV1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_OnlineDataV1Data_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OnlineDataRoleAttrObjV1)
}
OnlineDataRoleAttrObjV1::OnlineDataRoleAttrObjV1(const OnlineDataRoleAttrObjV1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&value_) -
    reinterpret_cast<char*>(&id_)) + sizeof(value_));
  // @@protoc_insertion_point(copy_constructor:OnlineDataRoleAttrObjV1)
}

void OnlineDataRoleAttrObjV1::SharedCtor() {
  _cached_size_ = 0;
  id_ = -1;
  value_ = -1;
}

OnlineDataRoleAttrObjV1::~OnlineDataRoleAttrObjV1() {
  // @@protoc_insertion_point(destructor:OnlineDataRoleAttrObjV1)
  SharedDtor();
}

void OnlineDataRoleAttrObjV1::SharedDtor() {
}

void OnlineDataRoleAttrObjV1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OnlineDataRoleAttrObjV1::descriptor() {
  protobuf_OnlineDataV1Data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OnlineDataV1Data_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OnlineDataRoleAttrObjV1& OnlineDataRoleAttrObjV1::default_instance() {
  protobuf_OnlineDataV1Data_2eproto::InitDefaults();
  return *internal_default_instance();
}

OnlineDataRoleAttrObjV1* OnlineDataRoleAttrObjV1::New(::google::protobuf::Arena* arena) const {
  OnlineDataRoleAttrObjV1* n = new OnlineDataRoleAttrObjV1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OnlineDataRoleAttrObjV1::Clear() {
// @@protoc_insertion_point(message_clear_start:OnlineDataRoleAttrObjV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    id_ = -1;
    value_ = -1;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool OnlineDataRoleAttrObjV1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OnlineDataRoleAttrObjV1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional sint32 Id = 1 [default = -1];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_id();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional float Value = 2 [default = -1];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {
          set_has_value();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OnlineDataRoleAttrObjV1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OnlineDataRoleAttrObjV1)
  return false;
#undef DO_
}

void OnlineDataRoleAttrObjV1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OnlineDataRoleAttrObjV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional sint32 Id = 1 [default = -1];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(1, this->id(), output);
  }

  // optional float Value = 2 [default = -1];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->value(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:OnlineDataRoleAttrObjV1)
}

::google::protobuf::uint8* OnlineDataRoleAttrObjV1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OnlineDataRoleAttrObjV1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional sint32 Id = 1 [default = -1];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(1, this->id(), target);
  }

  // optional float Value = 2 [default = -1];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->value(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:OnlineDataRoleAttrObjV1)
  return target;
}

size_t OnlineDataRoleAttrObjV1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OnlineDataRoleAttrObjV1)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional sint32 Id = 1 [default = -1];
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::SInt32Size(
          this->id());
    }

    // optional float Value = 2 [default = -1];
    if (has_value()) {
      total_size += 1 + 4;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OnlineDataRoleAttrObjV1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OnlineDataRoleAttrObjV1)
  GOOGLE_DCHECK_NE(&from, this);
  const OnlineDataRoleAttrObjV1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OnlineDataRoleAttrObjV1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OnlineDataRoleAttrObjV1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OnlineDataRoleAttrObjV1)
    MergeFrom(*source);
  }
}

void OnlineDataRoleAttrObjV1::MergeFrom(const OnlineDataRoleAttrObjV1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OnlineDataRoleAttrObjV1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      id_ = from.id_;
    }
    if (cached_has_bits & 0x00000002u) {
      value_ = from.value_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OnlineDataRoleAttrObjV1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OnlineDataRoleAttrObjV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OnlineDataRoleAttrObjV1::CopyFrom(const OnlineDataRoleAttrObjV1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OnlineDataRoleAttrObjV1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OnlineDataRoleAttrObjV1::IsInitialized() const {
  return true;
}

void OnlineDataRoleAttrObjV1::Swap(OnlineDataRoleAttrObjV1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OnlineDataRoleAttrObjV1::InternalSwap(OnlineDataRoleAttrObjV1* other) {
  using std::swap;
  swap(id_, other->id_);
  swap(value_, other->value_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OnlineDataRoleAttrObjV1::GetMetadata() const {
  protobuf_OnlineDataV1Data_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OnlineDataV1Data_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OnlineDataRoleAttrObjV1

// optional sint32 Id = 1 [default = -1];
bool OnlineDataRoleAttrObjV1::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void OnlineDataRoleAttrObjV1::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void OnlineDataRoleAttrObjV1::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void OnlineDataRoleAttrObjV1::clear_id() {
  id_ = -1;
  clear_has_id();
}
::google::protobuf::int32 OnlineDataRoleAttrObjV1::id() const {
  // @@protoc_insertion_point(field_get:OnlineDataRoleAttrObjV1.Id)
  return id_;
}
void OnlineDataRoleAttrObjV1::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataRoleAttrObjV1.Id)
}

// optional float Value = 2 [default = -1];
bool OnlineDataRoleAttrObjV1::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void OnlineDataRoleAttrObjV1::set_has_value() {
  _has_bits_[0] |= 0x00000002u;
}
void OnlineDataRoleAttrObjV1::clear_has_value() {
  _has_bits_[0] &= ~0x00000002u;
}
void OnlineDataRoleAttrObjV1::clear_value() {
  value_ = -1;
  clear_has_value();
}
float OnlineDataRoleAttrObjV1::value() const {
  // @@protoc_insertion_point(field_get:OnlineDataRoleAttrObjV1.Value)
  return value_;
}
void OnlineDataRoleAttrObjV1::set_value(float value) {
  set_has_value();
  value_ = value;
  // @@protoc_insertion_point(field_set:OnlineDataRoleAttrObjV1.Value)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
