// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestModuleV1Data.proto

#ifndef PROTOBUF_TestModuleV1Data_2eproto__INCLUDED
#define PROTOBUF_TestModuleV1Data_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "PublicStruct.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TestModuleV1Data_2eproto();
void protobuf_AssignDesc_TestModuleV1Data_2eproto();
void protobuf_ShutdownFile_TestModuleV1Data_2eproto();

class TestModuleDataV1;
class TestModuleUselessV1;

// ===================================================================

class TestModuleDataV1 : public ::google::protobuf::Message {
 public:
  TestModuleDataV1();
  virtual ~TestModuleDataV1();

  TestModuleDataV1(const TestModuleDataV1& from);

  inline TestModuleDataV1& operator=(const TestModuleDataV1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestModuleDataV1& default_instance();

  void Swap(TestModuleDataV1* other);

  // implements Message ----------------------------------------------

  TestModuleDataV1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestModuleDataV1& from);
  void MergeFrom(const TestModuleDataV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional sint32 Field = 1 [default = -1];
  inline bool has_field() const;
  inline void clear_field();
  static const int kFieldFieldNumber = 1;
  inline ::google::protobuf::int32 field() const;
  inline void set_field(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:TestModuleDataV1)
 private:
  inline void set_has_field();
  inline void clear_has_field();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 field_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_TestModuleV1Data_2eproto();
  friend void protobuf_AssignDesc_TestModuleV1Data_2eproto();
  friend void protobuf_ShutdownFile_TestModuleV1Data_2eproto();

  void InitAsDefaultInstance();
  static TestModuleDataV1* default_instance_;
};
// -------------------------------------------------------------------

class TestModuleUselessV1 : public ::google::protobuf::Message {
 public:
  TestModuleUselessV1();
  virtual ~TestModuleUselessV1();

  TestModuleUselessV1(const TestModuleUselessV1& from);

  inline TestModuleUselessV1& operator=(const TestModuleUselessV1& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestModuleUselessV1& default_instance();

  void Swap(TestModuleUselessV1* other);

  // implements Message ----------------------------------------------

  TestModuleUselessV1* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TestModuleUselessV1& from);
  void MergeFrom(const TestModuleUselessV1& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:TestModuleUselessV1)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_TestModuleV1Data_2eproto();
  friend void protobuf_AssignDesc_TestModuleV1Data_2eproto();
  friend void protobuf_ShutdownFile_TestModuleV1Data_2eproto();

  void InitAsDefaultInstance();
  static TestModuleUselessV1* default_instance_;
};
// ===================================================================


// ===================================================================

// TestModuleDataV1

// optional sint32 Field = 1 [default = -1];
inline bool TestModuleDataV1::has_field() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestModuleDataV1::set_has_field() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestModuleDataV1::clear_has_field() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestModuleDataV1::clear_field() {
  field_ = -1;
  clear_has_field();
}
inline ::google::protobuf::int32 TestModuleDataV1::field() const {
  return field_;
}
inline void TestModuleDataV1::set_field(::google::protobuf::int32 value) {
  set_has_field();
  field_ = value;
}

// -------------------------------------------------------------------

// TestModuleUselessV1


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TestModuleV1Data_2eproto__INCLUDED
